version: '3'

networks:
  traefik_net:
    external: true

services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    command:
      --api.insecure=true
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --providers.file.directory=/data/
      --entrypoints.web.address=:80
      --entrypoints.websecure.address=:443

      --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}
      --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      --certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    volumes:
      - ./confs:/data:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.middlewares=admin-auth@file"
      # Global redirect to https
      - "traefik.http.routers.upgrade-insecure.rule=hostregexp(`{host:.+}`)"

